- name: Check if subscription-manager is installed
  command: which subscription-manager
  register: subscription_manager_check
  when: ansible_os_family == "RedHat"
  ignore_errors: True

- name: Refresh subscription-manager certificates on the instances
  become: yes
  command: subscription-manager refresh
  when: ansible_os_family == "RedHat" and subscription_manager_check.rc == 0
  ignore_errors: True