---
- name: Extract PEM from service account file
  copy: content="{{ (lookup('file', gce_service_account_keyfile ) | from_json ).private_key }}" dest=/tmp/gce.pem mode=0600
- name: Templatize environment script
  template: src=inventory.j2.sh dest=/tmp/inventory.sh mode=u+rx
