---
- name: Modify the node configuration
  replace:
      dest: /etc/origin/node/node-config.yaml
      regexp: '^(.*)perFSGroup: (\s+.*)?$'
      replace:  '\1 perFSGroup: {{ provision_gce_emptydir_quota | default("2048Mi") }}\2'
      backup: yes
  notify:
  - restart atomic-openshift-node
