# This playbook launches a new cluster or converges it if already launched

- import_playbook: provision.yaml

- hosts: localhost
  tasks:
  - meta: refresh_inventory

- import_playbook: configure.yaml
