# This playbook launches a new cluster or converges it if already launched

- name: Ensure all cloud resources necessary for the cluster, including instances, have been started
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - gce-provision
    - gce-dynamic-inventory

- hosts: localhost
  tasks:
  - meta: refresh_inventory

- include: configure.yaml
