# This playbook should converge a cluster to the desired major version, or perform incremental updates if no major version change is required

- hosts: localhost
  connection: local
  roles:
    - gce-instance-groups

- hosts: cluster_hosts
  roles:
    - gce-cluster-variables

# TODO: make this parameterizeable? That would make this a dynamic playbook, which has consequences for
#   syntax checking.
- include: /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_7/upgrade.yml
