- hosts: localhost
  gather_facts: yes
  roles:
    - instance-groups

- hosts: localhost
  gather_facts: no
  roles:
    - validate-public

- hosts: masters
  gather_facts: no
  roles:
    - validate-masters

# Not useful
# - hosts: masters
#  gather_facts: yes
#  roles:
#    - validate-etcd

# Temporarily disabled
# - hosts: primary_master
#   gather_facts: no
#   roles:
#    - validate-app
